# Generated by Django 2.2 on 2019-04-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('ro_community', models.CharField(max_length=50)),
                ('rw_community', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('enable_password', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(choices=[('ASA', 'ASA'), ('Router', 'Router'), ('Switch', 'Switch')], max_length=10)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
